version: '3'

services:
  autocompletenode:
    restart: always
    build: ./autocomplete-node
    ports:
      - '3001:3001'
      - '4001:8081'
    volumes:
      - /app/node_modules
      - ./autocomplete-node:/app
    container_name: zahramaslavi/autocomplete-node
    networks:
      - app-network

  autocompletereact:
    restart: always
    build: ./autocomplete
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./autocomplete:/app
    container_name: zahramaslavi/autocomplete-react
    depends_on:
      - autocompletenode
    networks:
      - app-network
  redis-server:
    image: 'redis'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge