name: CI for Front-end and Back-end

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install front-end dependencies
        working-directory: autocomplete
        run: yarn install

      - name: Run front-end tests
        working-directory: autocomplete
        run: yarn test

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install back-end dependencies
        working-directory: autocomplete-node
        run: yarn docker-build

      - name: Run back-end tests
        working-directory: autocomplete-node
        run: yarn docker-dev-test
  
